config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :subscribes
  resources :courses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/index', to: 'home#index', as: 'index'
  get '/corsi', to: 'home#corsi', as: 'corsi'
  get '/iscrizione', to: 'home#iscrizione', as: 'iscrizione'
  

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    has_one_attached :cover
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, only: %i[ new show edit update destroy ]
  before_action :set_course, only: %i[ new show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Corso creato con successo" }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Corso aggiornato con successo." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Corso eliminato con successo" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:tipo, :descrizione, :benefici, :orari, :ore, :partecipanti, :cover)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
    
    def corsi
    end

    def iscrizione
    end
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController
  before_action :authenticate_user!, only: %i[ new show edit update destroy ]
  before_action :set_course, only: %i[ new show edit update destroy ]

  # GET /subscribes or /subscribes.json
  def index
    @subscribes = Subscribe.all
  end

  # GET /subscribes/1 or /subscribes/1.json
  def show
  end

  # GET /subscribes/new
  def new
    @subscribe = Subscribe.new
  end

  # GET /subscribes/1/edit
  def edit
  end

  # POST /subscribes or /subscribes.json
  def create
    @subscribe = Subscribe.new(subscribe_params)

    respond_to do |format|
      if @subscribe.save
        format.html { redirect_to @subscribe, notice: "Subscribe was successfully created." }
        format.json { render :show, status: :created, location: @subscribe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscribe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribes/1 or /subscribes/1.json
  def update
    respond_to do |format|
      if @subscribe.update(subscribe_params)
        format.html { redirect_to @subscribe, notice: "Subscribe was successfully updated." }
        format.json { render :show, status: :ok, location: @subscribe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscribe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribes/1 or /subscribes/1.json
  def destroy
    @subscribe.destroy
    respond_to do |format|
      format.html { redirect_to subscribes_url, notice: "Subscribe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscribe
      @subscribe = Subscribe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscribe_params
      params.require(:subscribe).permit(:cognome, :nome, :indirizzo, :email, :cellulare)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :tipo %>
    <%= form.text_field :tipo, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :descrizione %>
    <%= form.text_field :descrizione, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :benefici %>
    <%= form.text_field :benefici, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :orari %>
    <%= form.text_field :orari, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :ore %>
    <%= form.number_field :ore, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :partecipanti %>
    <%= form.text_field :partecipanti, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label 'Copertina' %>
    <%= form.file_field :cover,  class:'form-control' %>
  </div>

  <div class="form-group">
  <%= form.submit 'Crea corso', class:"btn btn-dark btn-block" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Modifica il corso</h1>

<%= render 'form', course: @course %>

<%= link_to 'Mostra', @course, class:"btn btn-dark btn-block" %> |
<%= link_to 'Torna Indietro ', courses_path, class:"btn btn-dark btn-block" %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scopri i nostri corsi</h1>

<table class="table table-dark table-striped">
<div class=
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Orari</th>
      <th>Ore</th>
      <th>Partecipanti</th>
      <th>Foto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.tipo %></td>
        <td><%= course.orari %></td>
        <td><%= course.ore %></td>
        <td><%= course.partecipanti %></td>
        <td> 
         <% if course.cover.attached? %>
          <%= image_tag url_for(course.cover), class: 'w-50'%>
         <% end %>
        </td>
        <td><%= link_to '📟 Mostra', course, class:"btn btn-outline-dark" %></td>
        <td><%= link_to '✏️ Modifica', edit_course_path(course), class:"btn btn-outline-dark" %></td>
        <td><%= link_to '❌ Elimina', course, method: :delete, data: { confirm: '✔️  Sei sicuro di voler eliminare il corso?  ❌' }, class:"btn btn-outline-dark" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuovo corso', new_course_path, class:"btn btn-dark btn-block" %>

app/views/courses/new.html.erb
<h1>Nuovo Corso</h1>

<%= render 'form', course: @course %>

<%= link_to 'Torna indietro', courses_path, class:"btn btn-dark btn-block" %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% if @course.cover.attached? %>
    <%= image_tag url_for(@course.cover), class:'rounded mx-auto d-block'%>
    <% end %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @course.tipo  %>
</p>

<p>
  <strong>Descrizione:</strong>
  <%= @course.descrizione %>
</p>

<p>
  <strong>Benefici:</strong>
  <%= @course.benefici %>
</p>

<p>
  <strong>Orari:</strong>
  <%= @course.orari %>
</p>

<p>
  <strong>Ore:</strong>
  <%= @course.ore %>
</p>

<p>
  <strong>Partecipanti:</strong>
  <%= @course.partecipanti %>
</p>



<%= link_to 'Modifica', edit_course_path(@course), class:"btn btn-dark btn-block" %> |
<%= link_to 'Torna indietro', courses_path, class:"btn btn-dark btn-block" %>

app/views/home/corsi.html.erb
<p>aaa</p>

app/views/home/index.html.erb
    <link rel="stylesheet" href="index.css">
    <br><% if user_signed_in? %>
    Benvenuto <b><%= current_user.email %></b>!
    <br><%= link_to "Log Out", destroy_user_session_path, method: :delete %>
  <% end %> <br>  
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="https://calisthenicsmilano.com/wp-content/uploads/2021/04/bloheader_blog.jpg" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
            <h2>Grazie agli allenamenti</h2>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://calisthenicsmilano.com/wp-content/uploads/2020/08/calisthenics_milano_chisiamo.jpg" alt="Second slide">
            <div class="carousel-caption d-none d-md-block">
            <h2>Insegnanti qualificati</h2>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://calisthenicsmilano.com/wp-content/uploads/2020/10/calisthenics_milano_principianti.jpg" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
            <h2>Spazi larghi rispettando le normative</h2>
            </div>
        </div>
    </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
</div>
</div>
</div>


            <div class="row">
                <h1 class="text-center"><b>Scopri i corsi più Richiesti</b> </h1>
            
            </div>
            
            <br>
        <div class="card-group">
            <div class="card">
                <img class="card-img-top" src="https://www.hilifesportfitness.it/wp-content/uploads/32395-410x200.jpg" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Alternativa sportiva</h5>
                        <p>Il corso di Aerotonic prevede un programma di condizionamento muscolare e cardio-vascolare con esercizi strutturati mediante cambi di intensità abbinati ad accompagnamento musicale ritmato.</p>
                        <p class="card-text"><small class="text-muted">Ultimo aggiornamento: 08/06/2021</small></p>
                    </div>
            </div>
            <div class="card">
                <img class="card-img-top" src="https://www.hilifesportfitness.it/wp-content/uploads/2017/08/corso-hilife-amakafit-410x200.jpg" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Amaka Fit</h5>
                        <p>Si tratta di un training studiato ad hoc per lavorare su tutte le capacità motorie fondamentali nella crescita, come forza, velocità, resistenza e coordinazione, ovvero un allenamento a 360°, tramite attività dinamiche e progressive.</p>
                        <p class="card-text"><small class="text-muted">Ultimo aggiornamento: 08/06/2021</small></p>
                    </div>
            </div>
            <div class="card">
                <img class="card-img-top" src="https://www.hilifesportfitness.it/wp-content/uploads/2017/08/attivita%CC%80-fisica-adattata-410x200.jpg" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Attività fisica adattata(A.F.A.)</h5>
                        <p>Se quello che si cerca è un corso diverso, innovativo e curioso, iniziare Amaka Fit è l’ideale perché con questo allenamento alleni i muscoli e perdi peso mentre sei in aria. Amaka Fit è una tipologia di allenamento che utilizza un tessuto appeso come unico strumento per esercitarsi.</p>
                        <p class="card-text"><small class="text-muted">Ultimo aggiornamento: 08/06/2021</small></p>
                    </div>
                </div>
            </div>
        </div>
    </div>






</div>
<br>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="it">
  <head>



    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="application.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
  <meta charset="utf-8">
      <p class="notice" ><%= notice %>
      <p class="alert" ><%= alert %>
      <script href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
      <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light">
        
        <div class="container">
          <a class="navbar-brand" href="/index">GymFit</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="/courses">Corsi</a>
            <a class="nav-link active" aria-current="page" href="/subscribes">Iscriviti</a>
            </div>
          </div>
        </div>
      </nav><br>
<%= yield %>



</body>


    <div class="footer-basic">
        <footer>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="/index">GymFit</a></li>
                <li class="list-inline-item"><a href="/courses">Corsi</a></li>
                <li class="list-inline-item"><a href="/subscribes">Iscriviti</a></li>
            </ul>
            <p class="copyright"><b>GymFit©</b> by Daniele Pavan © 2021</p>
            <p class="copyright"><b>GymFit©</b> palestra che offre corsi online e anche in presenza</p>
            <p class="copyright">sempre alla mano con atrezzatura di ultima generazione. </p>
            <p class="copyright">Tutti i diritti riservati - All right reserved </p>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>


<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

</html>

app/views/subscribes/_form.html.erb
<%= form_with(model: subscribe) do |form| %>
  <% if subscribe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscribe.errors.count, "error") %> prohibited this subscribe from being saved:</h2>

      <ul>
        <% subscribe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :cognome %>
    <%= form.text_field :cognome, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :nome %>
    <%= form.text_field :nome, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :indirizzo %>
    <%= form.text_field :indirizzo, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :cellulare %>
    <%= form.text_field :cellulare, class:'form-control' %>
  </div>

  <div class="form-group">
  <%= form.submit 'Iscriviti gratuitamente.', class:"btn btn-dark btn-block" %>
  </div>
<% end %>

app/views/subscribes/edit.html.erb
<div class="p-3 mb-2 bg-info text-white"></div>
<h1 class="text-center"><b>Modifica iscrizione</b></h1>
<div class="p-3 mb-2 bg-info text-white"></div>

<%= render 'form', subscribe: @subscribe %>

<%= link_to 'Mostra', @subscribe %> |
<%= link_to 'Torna indietro', subscribes_path %>

app/views/subscribes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="p-3 mb-2 bg-info text-white"></div>
<h1 class="text-center"><b>Iscriviti a GymFit</b></h1>
<div class="p-3 mb-2 bg-info text-white"></div>


<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th>Cognome</th>
      <th>Nome</th>
      <th>Indirizzo</th>
      <th>Email</th>
      <th>Cellulare</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscribes.each do |subscribe| %>
      <tr>
        <td><%= subscribe.cognome %></td>
        <td><%= subscribe.nome %></td>
        <td><%= subscribe.indirizzo %></td>
        <td><%= subscribe.email %></td>
        <td><%= subscribe.cellulare %></td>
        <td><%= link_to '📟 Mostra', subscribe, class:"btn btn-outline-dark" %></td>
        <td><%= link_to '✏️ Modifica', edit_subscribe_path(subscribe), class:"btn btn-outline-dark" %></td>
        <td><%= link_to '❌ Elimina', subscribe, method: :delete, data: { confirm: '✔️  Sei sicuro di voler eliminare l&#39iscrizione?  ❌' }, class:"btn btn-outline-dark" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Iscriviti', new_subscribe_path,  class:"btn btn-dark btn-block" %>

app/views/subscribes/new.html.erb
<div class="p-3 mb-2 bg-info text-white"></div>
<h1 class="text-center"><b>Compila il modulo di iscrizione</b></h1>
<div class="p-3 mb-2 bg-info text-white"></div>

<%= render 'form', subscribe: @subscribe %>

<%= link_to 'torna indietro', subscribes_path, class:"btn btn-dark btn-block" %>

app/views/subscribes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cognome:</strong>
  <%= @subscribe.cognome %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @subscribe.nome %>
</p>

<p>
  <strong>Indirizzo:</strong>
  <%= @subscribe.indirizzo %>
</p>

<p>
  <strong>Email:</strong>
  <%= @subscribe.email %>
</p>

<p>
  <strong>Cellulare:</strong>
  <%= @subscribe.cellulare %>
</p>

<%= link_to 'Modifica', edit_subscribe_path(@subscribe), class:"btn btn-dark btn-block" %> |
<%= link_to 'Torna indietro', subscribes_path, class:"btn btn-dark btn-block" %>